/**
 * Represents the type of response generated by the AI.
 * Helps the frontend determine how to render the answer.
 */
export enum AIResponseType {
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  CHART = 'CHART',
  ERROR = 'ERROR'
}

/**
 * Data Transfer Object for the AI Assistant's response to a user query.
 */
export class AIQueryResponse {
  /**
   * @param answer The natural language text response.
   * @param type The categorization of the response for UI rendering.
   * @param visualizationData Optional structured data for rendering charts (if type is CHART).
   * @param debugInfo Optional metadata about the generation process (e.g., sources used).
   */
  constructor(
    public readonly answer: string,
    public readonly type: AIResponseType,
    public readonly visualizationData?: any,
    public readonly debugInfo?: {
      sources?: string[];
      processingTimeMs?: number;
    }
  ) {}

  /**
   * Factory method to create an error response.
   * @param message User-friendly error message.
   */
  static error(message: string): AIQueryResponse {
    return new AIQueryResponse(message, AIResponseType.ERROR);
  }
}