/**
 * Represents an actionable optimization suggestion generated by the AI assistant.
 * This entity encapsulates the advice, the rationale behind it, and the suggested action.
 */
export class Suggestion {
  /**
   * Unique identifier for the suggestion.
   */
  public readonly id: string;

  /**
   * The merchant identifier this suggestion belongs to.
   */
  public readonly merchantId: string;

  /**
   * The specific rule or heuristic ID that generated this suggestion.
   */
  public readonly ruleId: string;

  /**
   * A concise title for the suggestion.
   */
  public readonly title: string;

  /**
   * A detailed explanation of why this suggestion is being made (the rationale).
   */
  public readonly description: string;

  /**
   * The type of action recommended (e.g., "PRICE_ADJUSTMENT", "MARKETING_CAMPAIGN").
   */
  public readonly actionType: string;

  /**
   * A score representing the potential impact or importance of this suggestion (0-100).
   */
  public readonly impactScore: number;

  /**
   * Additional data needed to execute or display the suggestion (e.g., product IDs).
   */
  public readonly metadata: Record<string, unknown>;

  /**
   * When the suggestion was created.
   */
  public readonly createdAt: Date;

  /**
   * Indicates if the suggestion has been dismissed by the user.
   */
  private _isDismissed: boolean;

  /**
   * Creates a new Suggestion domain entity.
   * 
   * @param id - Unique UUID.
   * @param merchantId - Tenant UUID.
   * @param ruleId - Identifier of the generating rule.
   * @param title - Short headline.
   * @param description - Detailed rationale.
   * @param actionType - Category of action.
   * @param impactScore - Priority score (0-100).
   * @param metadata - Contextual data.
   */
  constructor(
    id: string,
    merchantId: string,
    ruleId: string,
    title: string,
    description: string,
    actionType: string,
    impactScore: number,
    metadata: Record<string, unknown> = {}
  ) {
    this.validate(id, merchantId, title, description, impactScore);

    this.id = id;
    this.merchantId = merchantId;
    this.ruleId = ruleId;
    this.title = title;
    this.description = description;
    this.actionType = actionType;
    this.impactScore = impactScore;
    this.metadata = metadata;
    this.createdAt = new Date();
    this._isDismissed = false;
  }

  /**
   * Validates the integrity of the suggestion data.
   */
  private validate(
    id: string,
    merchantId: string,
    title: string,
    description: string,
    impactScore: number
  ): void {
    if (!id || id.trim().length === 0) throw new Error('Suggestion ID is required.');
    if (!merchantId || merchantId.trim().length === 0) throw new Error('Merchant ID is required.');
    if (!title || title.trim().length === 0) throw new Error('Title is required.');
    if (!description || description.trim().length === 0) throw new Error('Description is required.');
    if (impactScore < 0 || impactScore > 100) throw new Error('Impact score must be between 0 and 100.');
  }

  /**
   * Marks the suggestion as dismissed by the user.
   */
  public dismiss(): void {
    this._isDismissed = true;
  }

  /**
   * Checks if the suggestion is currently dismissed.
   */
  public isDismissed(): boolean {
    return this._isDismissed;
  }

  /**
   * Determines if this is a high-priority suggestion based on the impact score.
   * @returns true if impact score is 75 or higher.
   */
  public isHighPriority(): boolean {
    return this.impactScore >= 75;
  }

  /**
   * Reconstructs a Suggestion from persistence.
   */
  public static reconstruct(
    id: string,
    merchantId: string,
    ruleId: string,
    title: string,
    description: string,
    actionType: string,
    impactScore: number,
    metadata: Record<string, unknown>,
    createdAt: Date,
    isDismissed: boolean
  ): Suggestion {
    const suggestion = new Suggestion(
      id,
      merchantId,
      ruleId,
      title,
      description,
      actionType,
      impactScore,
      metadata
    );
    // Bypass readonly for reconstruction
    (suggestion as any).createdAt = createdAt;
    (suggestion as any)._isDismissed = isDismissed;
    return suggestion;
  }
}